[metadata]
name = ai-code-review
version = 0.1.0
author = Евгений Птицын
description = AI-powered code review system for GitLab
license = AGPL-3.0

[options]
packages = find:
python_requires = >=3.11

[options.packages.find]
where = app

[coverage:run]
branch = True
source = app

[coverage:report]
omit =
    tests/*
    */__init__.py
    */migrations/*
exclude_lines =
    pragma: no cover
    if __name__ == .__main__.:
